### ISSUE TITLE
This helper is not working with php7

### ISSUE THREAD

**Issue by naveen84123** [martinbean/cakephp-thumbnail-helper#3]
Thumbnail helper is not working with php7. Will anyone tell me what should I do to make this helper compatible with php7.0?

**Comment by martinbean** [comment]
This helper was written a long time before PHP 7 was released. If you’re getting an error message, please provide it as that would make debugging a _lot_ easier.

**Comment by naveen84123** [comment]
I got the solution. 
we need to install :
sudo apt-get install php7.0-gd
GD and Image Functions library compatible with php7

**Comment by martinbean** [comment]
OK. So not an issue with the plugin code itself. You just need to install the correct PHP extension.
